spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA2/Vdsun0TzJF5ISqmRkMeuTPP7rzD48V5PjZsAUP9VuvTUXevjQheR+G/vFu4/7Z0fGz4TDwZ+kJgb1KjFYOZ2Bfd1qnFkEIE3Jt24U51EKzYMfticIr/qyirKHaDIPt2axhMcWjQQcLW2qM4qr2DeKDs6Q+PvkkBImXpbzPl8KUHQDL4PvB+cclDEWTzWB6tSLykTQiFSQsZneJX5tF42ppSvjbbd4qQQegyUMf12JY8rjmvuwr+cuQmcEVPEJ0hBCqkTBriLdr/MTTyzAPDMfkgNlgPX+D8M+WhejaZNb3BVfEx+HL3XUdUpfk7AnAx76F4s/VL2Hvb3zRtYoyBB1fTtYmUu3PPa/mihx5nDHic5d+oYIo6mL4j9tR7A8w='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBIKv2LASQHt99NLlCHNILMJ/TgamdSmazErwCFqOwBc4uJMwPz+ziRUqeOU7HJ8B6KD9k/ut3Q7hQkOV+3SJCoSgqi719lRX8Bap9hrR+gGTq06Op97Y7wwomjPoytkrOVev6UhzP4TvoVGNAJ1A2/oTSY8wTrn9qHrGXW49FyIkNnKtWeprk43QVld5CTcRfRhCgLxaCDfJQTDoZjs1kdyug5ChDK2nc9asGEfQmCw92i8lwOqP7z9jVBPog+liP5TIIRyMlicBndewtodbUzTiGZkWepZH08coV5bbW39HUwKBbUmoubwfcwKt1KpnPraVP3pMt5/nJDYwJPcM+8YzXPBxSsrtNMAh6AuGUrn3KzMrhwniWAM6US55+Ccs8='

gateway:
  ip: 192.168.219.194

order_service:
  url: http://order-service/order-service/%s/orders